### ISSUE TITLE
It would be cool if we could tag pis and sort on those tags

### ISSUE THREAD

**Issue by PeterGrace** [PeterGrace/pi_director#14]
So for instance, if we have 20 pis in NYC, 20 in Denver, 20 in London, we might only want to see all of the NYC ones.  Or, if we had a tag "elevator-displays" and wanted to see all of them at once.

**Comment by alexlmiller** [comment]
I came up with this!

+1

**Comment by PeterGrace** [comment]
This is mostly done, it just needs the tag management screen to be completed

**Comment by PeterGrace** [comment]
completed in 9bd1ce24bbfc7a6bea41647154b45af87b4c09ce
