### ISSUE TITLE
PIFM versioning

### ISSUE THREAD

**Issue by selfcommit** [PeterGrace/pi_director#34]
Currently there's an issue where PIFM is aware of information recieved from pi_director, and information currently in its cache, but not aware of state.
(ex: cache and url say screen should be 180, but it happens to be 270)

I see this happen most often while testing changes to the pifm agent.

Suggested solution: 
include a version hash of the pifm_agent file.  The agent should compare its cached version to the servers version at each checkin.  The servers version would update as part of the server init process.

We might be able to leverage this as a way of mass updating pi's to the newest PIFM in the future.

**Comment by PeterGrace** [comment]
Although what I think you're asking for ("we think status is X, but it really is Y"), your versioning paragraph doesn't solve that.  However, I have at least enabled pifm_agent.py to auto-update with 29bc5b09661d92acfb70ad2275b0f995fc733a31
